### ISSUE TITLE
VMware Encryption at rest is available now

### ISSUE THREAD

**Issue by simonrowan** [UKCloud/documentation#1211] opened 2020-11-17 11:09 UTC
The new pods, backed by Pure storage now support encryption at rest, this article says it is not available

**Comment by suehighmoor** [comment] 2020-12-08 12:32
@simonrowan - sorry it's taken me a while to get to this. Could you just confirm which article you're referring to and I'll take a look. Thanks!

**Comment by suehighmoor** [comment] 2021-09-24 10:05
PR #1969 updates the services by region and VMware FAQ articles to indicate that D@RE is available in regions 13 and 14

**Comment by simonrowan** [comment] 2021-09-24 10:08
Hi Sue,

I've left UKCloud so shouldn't be getting these emails any more

Cheers

**Comment by suehighmoor** [comment] 2021-09-24 10:12
Hi Simon,

You’re getting this one because you raised an issue against the repository, so it’s separate from your UKCloud membership. I checked and you were correctly removed from the UKCloud org, so that’s all good. You’ll probably get one more email when the PR that fixes the issue is merged and then that should be it.

Thanks for raising though.

Sue


Sue Highmoor - 
Documentation Manager
***@***.***
+44 1252 936020
www.ukcloud.com
A8, Cody Technology Park, Ively Road, Farnborough, GU14 0LX
Notice: This message contains information that may be privileged or confidential and is the property of UKCloud Ltd. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorised to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message. UKCloud reserves the right to monitor all e-mail communications through its networks. UKCloud Ltd is registered in England and Wales: Company No: 07619797. Registered office: Hartham Park, Hartham, Corsham, Wiltshire SN13 0RP.

**Closed** 2021-09-30 10:39 UTC
Labels: VMware, user suggestion
